In [1]:
import statsmodels.api as sm

In [3]:
import numpy as np

In [29]:
X = np.array([1, 2, 3, 4, 5, 6, 7])

In [30]:
y = np.array([2, 7, -5, -4, 11, 18, 19])

In [31]:
regr = sm.OLS(y, X).fit()

In [10]:
prediction = regr.get_prediction()

In [13]:
prediction.summary_frame()

mean   mean_se  mean_ci_lower  mean_ci_upper  obs_ci_lower  \
0   2.007143  0.632449       0.459596       3.554689    -16.368954   
1   4.014286  1.264898       0.919193       7.109379    -14.556272   
2   6.021429  1.897346       1.378789      10.664068    -12.868784   
3   8.028571  2.529795       1.838385      14.218757    -11.300278   
4  10.035714  3.162244       2.297982      17.773447     -9.842880   
5  12.042857  3.794693       2.757578      21.328136     -8.487667   
6  14.050000  4.427142       3.217175      24.882825     -7.225247   

   obs_ci_upper  
0     20.383239  
1     22.584844  
2     24.911641  
3     27.357421  
4     29.914309  
5     32.573381  
6     35.325247

In [14]:
prediction.conf_int()

array([[ 0.45959637,  3.55468934],
       [ 0.91919274,  7.10937869],
       [ 1.37878911, 10.66406803],
       [ 1.83838549, 14.21875737],
       [ 2.29798186, 17.77344671],
       [ 2.75757823, 21.32813606],
       [ 3.2171746 , 24.8828254 ]])

In [15]:
prediction.se_mean

array([0.63244881, 1.26489762, 1.89734643, 2.52979524, 3.16224405,
       3.79469286, 4.42714167])

In [16]:
prediction.se_obs

array([7.50991352, 7.58938571, 7.72002157, 7.8992831 , 8.12395205,
       8.3903816 , 8.69473363])

In [19]:
prediction.summary_frame()['mean']

0     2.007143
1     4.014286
2     6.021429
3     8.028571
4    10.035714
5    12.042857
6    14.050000
Name: mean, dtype: float64

In [22]:
regr.remove_data()

In [32]:
regr.predict(exog=X)

array([ 2.00714286,  4.01428571,  6.02142857,  8.02857143, 10.03571429,
       12.04285714, 14.05      ])

In [33]:
regr.params

array([2.00714286])

In [34]:
a = np.array([1, 2, 3, 4])

In [35]:
b = np.array([3, 5, 7, 9])

In [36]:
weights = sm.OLS(b, sm.add_constant(a)).fit().params

In [37]:
weights

array([1., 2.])

In [38]:
weights2 = np.array([3, 4])

In [39]:
for b, a in [weights, weights2]:
    print(a, b)

1.9999999999999993 1.0
4 3


In [40]:
weights*2 + 1

array([3., 5.])

In [41]:
import scipy.stats

In [42]:
help(scipy.stats.gaussian_kde)

Help on class gaussian_kde in module scipy.stats.kde:

class gaussian_kde(builtins.object)
 |  gaussian_kde(dataset, bw_method=None, weights=None)
 |  
 |  Representation of a kernel-density estimate using Gaussian kernels.
 |  
 |  Kernel density estimation is a way to estimate the probability density
 |  function (PDF) of a random variable in a non-parametric way.
 |  `gaussian_kde` works for both uni-variate and multi-variate data.   It
 |  includes automatic bandwidth determination.  The estimation works best for
 |  a unimodal distribution; bimodal or multi-modal distributions tend to be
 |  oversmoothed.
 |  
 |  Parameters
 |  ----------
 |  dataset : array_like
 |      Datapoints to estimate from. In case of univariate data this is a 1-D
 |      array, otherwise a 2-D array with shape (# of dims, # of data).
 |  bw_method : str, scalar or callable, optional
 |      The method used to calculate the estimator bandwidth.  This can be
 |      'scott', 'silverman', a scalar constant